# Generated by Django 5.0.3 on 2024-04-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='experience_level_en',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='experience_level_fi',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='experience_level_ja',
        ),
        migrations.RemoveField(
            model_name='movementtranslation',
            name='experience_level',
        ),
    ]
