# Generated by Django 4.2.6 on 2024-02-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_addition_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='name',
            field=models.CharField(default='push', max_length=100),
        ),
    ]
