# Generated by Django 4.2.6 on 2024-02-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_id_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='id',
        ),
    ]
