# Generated by Django 5.0.3 on 2024-04-11 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_movement_experience_level_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title_ja',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='answer_en',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='answer_fi',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='answer_ja',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_en',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_fi',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_ja',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ConversationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('fi', 'Finnish')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='QATranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ja', 'Japanese'), ('fi', 'Finnish')], max_length=10)),
                ('question', models.TextField(max_length=100)),
                ('answer', models.TextField(max_length=1000)),
                ('qa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='backend.qa')),
            ],
        ),
    ]
