# Generated by Django 4.2.6 on 2024-02-15 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_token'),
        ('backend', '0003_alter_user_password_alter_user_username'),
    ]

    operations = [
    ]
