# Generated by Django 4.2.6 on 2024-02-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_trainingplan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemovementconnection',
            name='sets',
        ),
    ]
