# Generated by Django 4.2.6 on 2024-02-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_merge_20240215_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addition',
            name='tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tracking'),
        ),
    ]
