# Generated by Django 4.2.6 on 2024-02-16 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_addition_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addition',
            name='date',
        ),
        migrations.AddField(
            model_name='addition',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='addition',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
