# Generated by Django 4.2.6 on 2024-02-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_exercisemovementconnection_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlanMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.movement')),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.trainingplan')),
            ],
        ),
    ]
