# Generated by Django 4.2.6 on 2024-02-16 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_addition_date_addition_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='date',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='date',
        ),
        migrations.AddField(
            model_name='exercise',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exercisemovementconnection',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='exercisemovementconnection',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='goal',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
