# Generated by Django 4.2.6 on 2024-03-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_trainingplanmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
