# Generated by Django 4.2.6 on 2024-02-17 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_exercise_date_remove_goal_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
