# Generated by Django 5.0.2 on 2024-03-06 06:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_goal_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
