# Generated by Django 4.2.6 on 2024-02-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_goal_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='unit',
            field=models.CharField(max_length=10),
        ),
    ]
