# Generated by Django 4.2.6 on 2024-02-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_goal_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemovementconnection',
            name='reps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercisemovementconnection',
            name='sets',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercisemovementconnection',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
