# Generated by Django 4.2.6 on 2024-03-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, null=True),
        ),
    ]
