# Generated by Django 4.2.6 on 2024-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_exercisemovementconnection_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemovementconnection',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
