# Generated by Django 4.2.6 on 2024-02-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_exercisemovementconnection_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='category',
        ),
    ]
