# Generated by Django 5.0.2 on 2024-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_trainingplan_experience_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='category',
            field=models.CharField(choices=[('triceps', 'Triceps'), ('biceps', 'Biceps'), ('shoulders', 'Shoulders'), ('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('core', 'Core'), ('other', 'Other')], default='other'),
        ),
    ]
