# Generated by Django 5.0.3 on 2024-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_movement_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20, null=True),
        ),
    ]
