# Generated by Django 5.0.3 on 2024-03-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_addition_goal_alter_addition_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='updated',
        ),
    ]
