# Generated by Django 5.0.3 on 2024-03-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_user_password_alter_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
